RNPurchases.podspec, ios/RNPurchases.m
Hi,
I added a podspec so the lib can be used with RN projects using CocoaPods to manage their dependencies.
People already using CocoaPods and running `react-native link react-native-purchases` will see it directly added to their `Podfile`.
I removed an `@import` statement which caused the CocoaPods build to fail. I believe it shouldn't break normal users not using CocoaPods, since `RNPurchases.h` already does `#import <Purchases/RCPurchases.h>` but let me know if it causes an issue. I haven't tested that scenario myself.
Cheers,
=> Add podspec

ios/RCPurchaserInfo+RNPurchases.m
Hi,
I got crashes on iOS 9.
I tracked it down to the use of `NSISO8601DateFormatter` which is only available starting iOS 10.
This lead to trying to insert nil strings in the dictionary and causing the actual crash.
Let me know what you think.
=> Fix crash on iOS < 10 as NSISO8601DateFormatter is unavailable there

scripts/download-purchases-framework.sh
For some reason unzip fails when installing on bitbucket pipelines. 
Creating the `temp` folder before unzipping resolves the problem.
#26
=> Create unzip folder before extracting.

android/src/main/java/com/reactlibrary/RNPurchasesMath.java, android/src/main/java/com/reactlibrary/RNPurchasesModule.java, android/src/main/java/com/reactlibrary/RNPurchasesPeriod.java, ios/SKProduct+RNPurchases.m
Fixes https://github.com/RevenueCat/react-native-purchases/issues/49
We have been sending introductory pricing for Android for a while, back we needed to add support to iOS. 
Android's `intro_price_period` returns the period in ISO8601 format (https://developer.android.com/reference/com/android/billingclient/api/SkuDetails.html#getintroductorypriceperiod) so we need to return the same format for iOS. To make things easier we also return `intro_price_period_unit` and a `intro_price_period_number_of_units`. For parsing ISO8601 to unit and number of units I have used the Java 8 implementation (cannot use Java 8 because our Android min version is 16).
=> Intro pricing in iOS

README.md
This adds up-to-date instructions on how to use react-native-purchases with [ExpoKit](https://docs.expo.io/versions/latest/expokit/expokit/), (aka: a "bare" Expo workflow). 
The newest version of ExpoKit supports React 59, and therefore supports the new version of react-native-purchases.
The old version of ExpoKit _cannot be published to Google Play_ as of August 1rst, 2019 due to [Android's 64-bit requirements](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html). It's also a nightmare hellscape to try and get anything working in. I recommend _not_ supporting the old version. 
ExpoKit does _not_ have a "Frameworks" folder. The frameworks live _in_ the `node_modules` folders, so creating a reference needs to come from there. …
=> Add ExpoKit Specific Instructions

index.d.ts, package.json, src/index.ts
Related https://github.com/RevenueCat/react-native-purchases/issues/72
We were not exporting the interfaces and types so they were not available for import. Also added types to the package.json, although it's not necessary since it's in the default location. Also added a prepublish to make sure we call `tsc` before publishing
=> Exports interfaces and types

android/src/main/AndroidManifest.xml, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesPackage.java, example/android/app/src/main/java/com/revenuecat/purchases_sample/MainApplication.java
Related to #114 
That PR forgot to change the reference in MainApplication. I also changed the package to ver `com.revenuecat.purchases.react` instead of `com.reactlibrary`
=> Changes package to com.revenuecat.purchases.react and fixes mainapplication

__tests__/index.test.js, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, example/app/screens/UpsellScreen.js, index.js, src/index.ts
There was a missing parameter when calling `RNPurchases.purchaseProduct`. Android was working because it was also missing it.
I reverted the example back and removed the discount stuff to keep it simple
=> Fix missing parameter in purchaseProduct

index.d.ts, index.js, src/index.ts
Invalidating the cache is simultaneously an advanced technique and attractive to beginners who might think they need to invalidate the cache on every app launch, so I added a link to our docs that explains how to work with the cache in normal circumstances.
This will update both index.ts, index.d.ts, and index.js.
See RevenueCat/purchases-ios#223
=> Update invalidatePurchaserInfoCache docs

README.md
The Trello board has been removed since we weren’t doing a good job of keeping it up to date and have decided to sunset it for now.
=> Removes old trello link from Readme

README.md
- moved cocoapods docs to the top of iOS section
- updated docs and gifs to include `PurchasesHybridCommon.framework`
=> update framework docs to include common framework

example/package.json, example/yarn.lock, yarn.lock
Should also fix https://github.com/RevenueCat/react-native-purchases/network/alert/example/yarn.lock/dot-prop/open
=> Removes npm-check-updates from package.json

__tests__/index.test.js, index.js, src/index.ts
We were passing a number instead of the expected string. The common files expect a string so I figured the easiest would be to just convert it in the JS level since we can't have nullable Integers as parameters in the React Native module.
https://github.com/RevenueCat/react-native-purchases/blob/develop/ios/RNPurchases.m#L111
=> Fixes purchaseDiscountedPackage/purchaseDiscountedProduct

RNPurchases.podspec
Which in turn updates `RevenueCat/purchases-ios` to `3.5.1`.
> Removes all references to ASIdentifierManager and advertisingIdentifier. This should help with some Kids apps being rejected.
=> Update dependency PurchasesHybridCommon to v1.3.1

android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
Fixes https://github.com/RevenueCat/react-native-purchases/issues/170
Looks like something changed in Android plugin 4.1.0 that we can't access BuildConfig. 
I figured the easiest would be to just hardcode the version directly, like we do in other plugins.
=> Removes usage of BuildConfig

RNPurchases.podspec, ios/PurchasesPlugin.swift, ios/RNPurchases-Bridging-Header.h, ios/RNPurchases.xcodeproj/project.pbxproj
- Adds `"ios/PurchasesHybridCommon.framework"` to the list of excluded files to avoid duplicated symbols errors
- Adds an empty swift file to the plugin and specifies the Swift Version in the podspec. I haven't seen this fixing the build errors in React Native 0.61.5 (possibly in more versions), but I don't think it hurts.
- Looks like the app won't compile until a swift file is added to the iOS project. In React Native 0.63.3 everything works fine.
=> Adds an empty swift file and excludes PurchasesHybridCommon.framework

package.json
There are a couple of references to paths that got broken in https://github.com/RevenueCat/react-native-purchases/pull/235
=> fix paths in package.json

.circleci/config.yml, examples/purchaseTester/ios/Podfile, examples/purchaseTester/ios/Podfile.lock, examples/purchaseTester/package.json, examples/purchaseTester/yarn.lock
Flipper was broken in 12.5. I found this issue which explains how to fix it and followed the steps https://github.com/facebook/react-native/issues/31480
=> Fix build of example app in Xcode 12.5

examples/MagicWeather/src/components/PackageItem/index.js
Cancelling a purchase causes an error as the whole Error object is passed as a description tot Alert.
=> Fix error on cancelling purchase

src/purchases.ts
Similar to `isAnonymous` (fixed in https://github.com/RevenueCat/react-native-purchases/pull/302 ), the returned type of `getAppUserId` is incorrect and should be a `Promise<string>` instead of a `string`
=> Fix types of getAppUserId

ios/RNPurchases.h
The current version of react-native-purchases does not build in a Expo SDK 44 project because of duplicate symbols.
```
› Compiling react-native-purchases Pods/RNPurchases » PurchasesPlugin.swift
❌  (/Users/yonom/Documents/GitHub/app/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h:14:1)
12 |  * events to be observed by JS.
13 |  */
> 14 | @interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTInvalidating>
| ^ duplicate interface definition for class 'RCTEventEmitter'
15 | 
16 | @property (nonatomic, weak) RCTBridge *bridge;
17 | @property (nonatomic, weak) RCTModuleRegistry *moduleRegistry;
❌  (/Users/yonom/Documents/GitHub/app/ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h:16:40)
14 | @interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTInvalidating>
15 …
```
=> Fix Expo SDK 44 compatibility

.circleci/config.yml
Updates to use [new executor type](https://circleci.com/docs/2.0/executor-types/#using-macos).
I also upgraded Xcode to 13.2.0
| Before | After |
|--------|------|
| <img width="526" alt="Screen Shot 2022-01-03 at 3 14 56 PM" src="https://user-images.githubusercontent.com/664544/147940853-c74f3a5a-8479-48bf-9762-decd316fffd1.png"> | <img width="642" alt="Screen Shot 2022-01-03 at 3 13 52 PM" src="https://user-images.githubusercontent.com/664544/147940716-91d273bf-f205-496d-8895-222343b76d4e.png"> |
| <img width="402" alt="Screen Shot 2022-01-03 at 3 08 09 PM" src="https://user-images.githubusercontent.com/664544/147940165-f46e51cc-926e-4f13-bd5c-85fef9c658f3.png"> | <img width="408" alt="Screen Shot 2022-01-03 at 3 13 21 PM" src="https://user-images.githubusercontent.com/664544/147940675-8 …
=> Update to gen2 circleCI machines

.circleci/config.yml, examples/purchaseTesterTypescript/android/settings.gradle, examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx, examples/purchaseTesterTypescript/ios/Podfile, examples/purchaseTesterTypescript/ios/Podfile.lock, examples/purchaseTesterTypescript/metro.config.js, examples/purchaseTesterTypescript/package.json, examples/purchaseTesterTypescript/react-native.config.js
Follow up to https://github.com/RevenueCat/react-native-purchases/pull/320
Use local repo for `react-native-purchases` instead of pointing to published version to use for local development
- New `react-native.config.js` to define local decency for auto linking
- Updated `metro.config.js ` to:
- Look at the root `package.json` with `nodeModulesPath` and `watchFolders`
- Set `resolverMainFields` to look at `source` so `react-native-purchases` doesn't use the compiled `dist` 
- Updated `.circleci/config.yml`
- Need to run `yarn install` (or `npm install`) in the root directory because this as local dependency needs its own `node_modules`
=> Setup local testing for PurchaseTester Typescript

.github/stale.yml
Our stalebot needs a few more labels to be sure we aren’t automatically closing issues that shouldn’t be closed.
New exempt labels are:
- pinned
- you can do this!
- triaged
=> adds more exempt labels

android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
Fix for https://github.com/RevenueCat/react-native-purchases/issues/309 by adding new required functions to `RNPurchasesModule.java`. 
Same fix was implemented in https://github.com/react-native-webrtc/react-native-webrtc/pull/1072 and it follows the official documentation https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript.
I tested it with this branch https://github.com/RevenueCat/react-native-purchases/pull/338 and it fixes the warning and the listener still works.
[CF-370]
[CF-370]: https://revenuecats.atlassian.net/browse/CF-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adds missing addListener and removeListeners functions to RNPurchasesModule.java

Gemfile.lock
We have a [security alert](https://github.com/RevenueCat/react-native-purchases/security/dependabot/3) due to a version of cocoapods-downloader. I've upgrade it in the Gemfile.lock to a safest one. I've found that the new version is inside the Cocoapods range as you can see [here](https://github.com/CocoaPods/CocoaPods/blob/1.10.2/Gemfile.lock#L117)
In the version 1.11.3 fo Cocoapods [they've updated to 1.5.1](https://github.com/CocoaPods/CocoaPods/blob/b544eb356238d90684d109333e728703226af9f6/Gemfile.lock#L58-L63) but is still affected by the issue
=> Upgrade cocoapods-download to 1.6.3 for security alert

src/purchaserInfo.ts
Inspired by https://github.com/RevenueCat/purchases-flutter/issues/361
The comment for entitlement's `willRenew` was wrong. Lifteime purchases will return `false`
=> Update willRenew comment - will be false for lifetime

.circleci/config.yml, apitesters/purchases.ts, apitesters/tsconfig.json
For [CSDK-143].
This relies on TypeScript compilation to detect type issues. A separate `tsconfig.json` inherits from the parent one to compile only these files.
`noUnusedLocals` and `noUnusedParameters` are set to `false` to ignore errors due to all these values being unused in the testers.
This PR only adds the main setup. See #360 for the rest of testers.
[CSDK-143]: https://revenuecats.atlassian.net/browse/CSDK-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Started APITesters

__tests__/index.test.js, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, apitesters/purchases.ts, ios/RNPurchases.m, src/purchases.ts
Depends on https://github.com/RevenueCat/purchases-hybrid-common/pull/170 (this won't compile until we point to PHC with that update).
Also depends on #361.
=> `Purchases.setUp`: added `usesStoreKit2IfAvailable`

__tests__/index.test.js, apitesters/customerInfo.ts, apitesters/enums.ts, apitesters/offerings.ts, apitesters/purchases.ts, src/customerInfo.ts, src/offerings.ts, src/purchases.ts
- Renamed `PurchasesStoreTransaction`
- Renamed `PurchasesStoreProduct`
- Renamed `PurchasesStoreProductDiscount`
- Removed deprecated `identify`/`reset`/`createAlias`
- Renamed `setUp` to `configure`
- Removed no loner needed `ATTRIBUTION_NETWORK`
- Removed deprecated `intro_price` properties in favor of the new one
For [CSDK-182].
See also https://github.com/RevenueCat/purchases-hybrid-common/pull/147
[CSDK-182]: https://revenuecats.atlassian.net/browse/CSDK-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Finished version 5.0 renames

.circleci/config.yml
Fixes [CSDK-332].
See https://app.circleci.com/pipelines/github/RevenueCat/react-native-purchases/1078/workflows/802f3ff0-15d6-4390-b67e-0ba8768c1996/jobs/3418/parallel-runs/0/steps/0-108
We use the `react-native-community/react-native` orb which relies on the existence of `Podfile.lock` files, but we removed those on https://github.com/RevenueCat/react-native-purchases/pull/355
[CSDK-332]: https://revenuecats.atlassian.net/browse/CSDK-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CircleCI: fixed `Podfile.lock` caching issues

fastlane/Fastfile
After #355, `Podfile.lock` isn't in the repo anymore, so `pod update` without it doesn't work.
=> Fixed `fastlane update_hybrid_common`

RELEASING.md
No reason to push the branch itself.
=> `RELEASING.md`: fixed push tags command

README.md
Looks like this was out of sync with [`package.json`](https://github.com/RevenueCat/react-native-purchases/blob/2b3825cc7625bbfdb8522082fe3579612f5cf763/package.json#L69).
=> `README`: updated minimum RN version

__tests__/index.test.js, apitesters/purchases.ts, ios/RNPurchases.m, scripts/setupJest.js, src/purchases.ts
Fixes #388 and [SDKONCALL-74]
[SDKONCALL-74]: https://revenuecats.atlassian.net/browse/SDKONCALL-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Renamed `restoreTransactions` to `restorePurchases`

CHANGELOG.latest.md, CHANGELOG.md, android/build.gradle, ios/RNPurchases.m, package.json, scripts/docs/index.html
⚠️⚠️ This is a pre-release version. ⚠️⚠️
This version of the SDK automatically uses StoreKit 2 APIs under the hood only for APIs that the RevenueCat team has determined work better than StoreKit 1.
New types that wrap native types from Apple, Google and Amazon, and we cleaned up the naming of other types and methods for a more consistent experience.
- `setUp` has been removed in favor of `configure`
- `identify` and `createAlias` have been removed in favor of `logIn`.
- `reset` has been removed in favor of `logOut`.
- `addAttributionData` has been removed in favor of `set<NetworkID> methods`.
- `PurchasesStoreProduct`: removed `intro_price_string`, `intro_price_period`, `intro_price_cycles`, `intro_price_period_unit`, `intro_price_period_number_of_units` in favor of new `introPrice: …
=> Release 5.0.0 Beta 2

.circleci/config.yml
Should fix https://app.circleci.com/pipelines/github/RevenueCat/react-native-purchases/1168/workflows/f3c95ce5-cf1c-4aad-ab49-728142637090/jobs/3689
Without this it was using a version that's no longer there (12.4.0).
=> `docs-deploy`: specify xcode version

RNPurchases.podspec, apitesters/attributes.ts, examples/purchaseTesterTypescript/App.tsx, ios/RNPurchases.m, src/purchases.ts
- Updated Hybrid Common to `4.1.0`
- Adds new `enableAdServicesAttributionTokenCollection` method
- Will essentially be a no-op on non-iOS platforms
- Updated typescript purchase tester example to call `Purchases.enableAdServicesAttributionTokenCollection`
=> Update Hybrid Common 4.1.0 and add AdServices

ios/RNPurchases.m
- Fixes comment that mentioned only supported in iOS 14.0 and above when its iOS 14.3+ and macOS 11.1+
=> Fix version comment for AdServices if not supported

apitesters/customerInfo.ts, examples/purchaseTesterTypescript/app/screens/CustomerInfoScreen.tsx, src/customerInfo.ts
**This is a breaking change!**
This will rename these 2 properties in `PurchasesStoreTransaction`:
- `revenueCatId` -> `transactionIdentifier`
- `productId` -> `productIdentifier`
=> [BREAKING] PurchasesStoreTransaction: Rename revenueCatId and productId to transactionIdentifier and productIdentifier

.circleci/config.yml
On the latest release tag, the docs deploy and prepare-next-version jobs didn't execute. I added a specification for those 2 jobs to run only on release-tags and that seems to fix the issue.
=> Specify branch for deployment dependencies

README.md
Add a link to the SDK reference to the README file – previously you would have had to follow the link to the RevenueCat docs, and then back to the SDK reference from there.
=> Add link to SDK reference to README

ios/RNPurchases.m
Fixes #401.
This was changed in https://github.com/RevenueCat/purchases-hybrid-common/pull/197 but it made this build fail.
=> `presentCodeRedemptionSheet`: fixed Catalyst build

README.md
unifying links to reference docs across all sdks
=> Add link to reference docs at the bottom

.circleci/config.yml, Gemfile.lock
We noticed how `prepare-next-version` is created from the release branches, which are then squashed and merged to `main`. This makes the snapshot bump branches to also have the commits from the merged release branch.
I added a step in the `prepare-next-version` job to switch to `main`. Alternatively, we could do this branch change in the fastlane plugin, but I wonder if we want to give the flexibility to execute the lane from any branch. Let me know what you think, I am open to move it there too.
=> Switch to main before preparing next release

.circleci/config.yml
Followup to https://github.com/RevenueCat/react-native-purchases/pull/432 to move the `prepare_next_version` job to a different workflow, since it won't be directly linked to the deploy workflow anymore.
=> Move prepare_next_version job to different workflow

README.md, examples/MagicWeather/README.md
The main README has been updated to match the purchases-ios version. This includes changes to the banner and RevenueCat description at the top and some miscellaneous sections (e.g., SDK Reference, Contributing). The "Installation" section related to React Native has been preserved.
The MagicWeather example app README has been updated to match the purchases-ios version, with instructions for both iOS and Android integration, and screenshots.
Thank you for contributing to react-native-purchases. Before pressing the "Create Pull Request" button, please provide the following:
- [ x ] A description about what and why you are contributing, even if it's trivial.
=> Updated main and MagicWeather README to match purchases-ios

Gemfile.lock
Bumps fastlane plugin to latest version, to fix this [issue with deployments](https://app.circleci.com/pipelines/github/RevenueCat/react-native-purchases/1379/workflows/497cb941-4dfc-46b8-a6d5-2fef0fcddc25/jobs/4438) by leveraging [this update to the plugin](https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/38)
=> bump fastlane plugin to latest version

ios/RNPurchases.m
It seems like the react native `addCustomerInfoUpdateListener` never gets called. Looking at the code it seems like at some point the iOS code changed to using receivedUpdatedCustomerInfo for the delegate instead of didReceiveUpdatedCustomerInfo. This is kind of obscured because you have to trace it through the hybrid shared project. I believe this should fix it though. Related PR which is a good place to start when trying to track down the initial change https://github.com/RevenueCat/purchases-ios/pull/1836
Here is a thread and someone else saying they ran into this error: https://community.revenuecat.com/sdks-51/addcustomerinfoupdatelistener-is-never-called-2073
There were previously no tests, it would be nice for this to be typesafe but I assume there is some reason it is not and so …
=> Use receivedUpdatedCustomerInfo instead of didReceiveUpdatedCustomerInfo

package.json
I've noticed everytime we update the version of `PurchasesHybridCommon` running `npx pod-install --quiet` fails and asks to run `pod update PurchasesHybridCommon`. Since we are using the pod-install package we can't run `pod repo update` so I figured we could just remove the lockfile before running `npx pod-install`.
I know this is not ideal, but I would like `yarn bootstrap` to prepare everything correctly. Please note the lockfiles are not pushed to the repository
=> Remove Podfile.locks when running `pods` script

DEVELOPMENT.md
`yarn ios` doesn't work anymore:
```
$ yarn ios
yarn run v1.22.17
error Command "ios" not found.
```
=> `DEVELOPMENT.md`: replaced `yarn` commands with `npx`

__tests__/index.test.js, apitesters/enums.ts, apitesters/purchases.ts, ios/RNPurchases.m, scripts/setupJest.js, src/errors.ts, src/purchases.ts
Deals with [CSDK-569](https://revenuecats.atlassian.net/browse/CSDK-569)
This PR adds 3 new methods to the react native API that will only be available in iOS 15+.
- `beginRefundRequestForActiveEntitlement`
- `beginRefundRequestForProduct`
- `beginRefundRequestForEntitlement`
In Android/iOS < 15, we will throw an `UnsupportedPlatformException`.
[CSDK-569]: https://revenuecats.atlassian.net/browse/CSDK-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add beginRefundRequest APIs for iOS 15+

DEVELOPMENT.md, examples/MagicWeather/package.json, examples/purchaseTesterTypescript/package.json, package.json
- Since MagicWeather uses a remote dependency, it didn't make sense to build it when doing `yarn bootstrap` from the root of the repository. It should be treated as a regular project and be built from its folder instead using `yarn` and `yarn pods`. Another reason for this is that MagicWeather was using ruby 2.7.2 and purchaseTester 2.7.4 which was causing issues when running pod install from the root (which uses 2.7.2). Anyways, I think this is cleaner and actually improves CI too.
- Added `pods` as a script to both MagicWeather and purchaseTester so the root package.json is more lean.
- I found out commands are chainable, so this is possible `yarn example ios`. `yarn example` changes the current working directory to purchaseTesterTypescript and `ios` will run the ios script in that …
=> Changes to npm scripts and DEVELOPMENT.md

examples/MagicWeather/package.json
Updaters the `react-native-reanimated` library verison in MagicWeather sample app to >2.10.0 to get rid of a vulnerability. 
Solves https://github.com/RevenueCat/react-native-purchases/security/dependabot/8
=> Update `react-native-reanimated` in MagicWeather example app

RNPurchases.podspec, __tests__/index.test.js, android/build.gradle, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, apitesters/offerings.ts, apitesters/purchases.ts, examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx, examples/purchaseTesterTypescript/package.json, ios/RNPurchases.m, migrations/v6-MIGRATION.md, scripts/setupJest.js, src/offerings.ts, src/purchases.ts
- Consume `SubscriptionOption`s and add `purchaseSubscriptionOption()`
- Set `isPersonalizedPrice`
- Consume and purchase with `presentedOfferingIdentifier `
- Bumped Purchases Hybrid Common to `5.0.0-beta.6` on Android and iOS
- Added `v6-MIGRATION.md` doc
New `SubscriptionOption` onto `PurchasesStoreProduct` with the following new interfaces and enums:
- `SubscriptionOption`
- `PricingPhase`
- `Period`
- `Price`
- `RecurrenceMode`
- `PeriodUnit`
```dart
const basePlan = storeProduct.subscriptionOptions?.filter((option) => { option.isBasePlan });
const defaultOffer = storeProduct.defaultOffer
const freeOffer = storeProduct.subscriptionOptions?.filter((option) => { !!option.freePhase });
const trialOffer = storeProduct.subscriptionOptions?.filter((option) => { !!option.introPhase });
``` …
=> [BC5] Add `SubscriptionOption`, `isPersonalizedPrice`, `presentedOfferingIdentifier` support

Gemfile.lock, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, fastlane/Fastfile
Updated plugin to use the changes from https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/46
This changes prevent updating the wrong version number when bumping either the version of the SDK or purchases-hybrid-common's version.
=> Update fastlane-plugin-revenuecat version

RNPurchases.podspec, android/build.gradle, apitesters/offerings.ts, examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx, scripts/setupJest.js, src/offerings.ts
Add `metadata` to `PurchasesOffering `
- Adds `metadata` to `PurchasesOffering`
- Adds API tester for `metadata`
- Adds new test
- Displays `metadata` in purchase tester app
- Bump to PHC `5.0.0-rc.1`
=> Add offering metadata

__tests__/index.test.js, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
We were only accepting parameters for the old `UpgradeInfo` object in the Android native side.
With this change, both `UpgradeInfo` and `GoogleProductChangeInfo` objects are accepted.
=> [DENG-418] Accept `GoogleProductChangeInfo` in `purchasePackage` in Android

migrations/v6-MIGRATION.md
Fix an incorrect method name in the V6 migration docs.
=> Fix V6 migration docs to use correct method name

__tests__/index.test.js, src/purchases.ts
Fix error from [this community post](https://community.revenuecat.com/sdks-51/react-native-purchases-purchasediscountedpackage-not-working-as-expected-3119?postid=10081#post10081)
- Add missing `null` fifth parameter when calling `RNPurchases.purchaseProduct`
=> Fix purchaseDiscountedPackage error with missing parameter

apitesters/offerings.ts, src/offerings.ts
As reported in #700. The typescript interface has specified the wrong type for metadata. We're not using typescript `Map`s, but simple objects for metadata This should be an object of key strings and unknown values.
=> Use correct type in offering metadata

android/src/main/java/com/revenuecat/purchases/react/GoogleUpgradeInfo.java, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
As reported in #763, we were using the `oldSKU` for google upgrades but the typescript interface only accepts `oldProductIdentifier` in the `purchaseSubscriptionOption` method. This makes sure all purchase methods have the same logic. Note that `purchaseSubscriptionOption` didn't exist before V5, but since some developers might have worked around the issue by using `oldSKU`, I think it's better to support that and avoid breaking their fixes.
=> Fix purchaseSubscriptionOption not accepting oldProductIdentifier

__tests__/index.test.js, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, apitesters/purchases.ts, examples/purchaseTesterTypescript/App.tsx, ios/RNPurchases.m, src/purchases.ts
See http://rev.cat/trusted-entitlements for more information.
Depends on https://github.com/RevenueCat/purchases-hybrid-common/pull/451
=> `Trusted Entitlements`: add support for setting `EntitlementVerificationMode`

examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx, examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
Fixes a couple of issues in the layout of footerView and full screen paywalls. 
Requires https://github.com/RevenueCat/purchases-ios/pull/3547
| Full Screen | Footer |
| :-: | :-: |
| ![Simulator Screenshot - iPhone 15 - 2024-01-02 at 17 36 45](https://github.com/RevenueCat/react-native-purchases/assets/3922667/02f86e0a-0e11-4622-847e-50b558496ece) | ![Simulator Screenshot - iPhone 15 - 2024-01-02 at 17 37 31](https://github.com/RevenueCat/react-native-purchases/assets/3922667/951a3b1a-006d-4b65-b115-e9dc5748ea9b) |
=> RevenueCatUI: FooterView and full screen paywall fixes

.circleci/config.yml
In #841 we separated the install dependencies command into 2 in order to fix an issue where the cache was wrong in different machine types. This unifies them back and uses a parameter instead.
=> Use parameter instead of multiple commands to install yarn dependencies

react-native-purchases-ui/ios/PaywallViewManager.m, react-native-purchases-ui/ios/PaywallViewWrapper.h, react-native-purchases-ui/ios/PaywallViewWrapper.m, react-native-purchases-ui/ios/RCPaywallFooterViewManager.m, react-native-purchases-ui/ios/UIView+Extensions.h, react-native-purchases-ui/ios/UIView+Extensions.m
This will only be needed if we update `createPaywallView` to return a `PaywallViewController`
```
@objc
public func createPaywallView() -> UIViewController {
let controller = PaywallViewController()
controller.delegate = self
return controller
}
```    
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> `PaywallViewManager`: added controller to UIVC hierarchy

.circleci/config.yml
Fixes https://app.circleci.com/pipelines/github/RevenueCat/react-native-purchases/2997/workflows/4b7f7128-c95d-46fe-847a-4011d6980d38/jobs/11357
`yarn` wasn't available on the previous image.
=> Fix `update-hybrid-common-versions`

react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
If we set only height it fixes the landscape mode
=> Fix for footer in lansdcape mode in iOS

__tests__/index.test.js, babel.config.js, package.json, yarn.lock
Updated versions to match `react-native-purchases-ui` devDependencies.
These fixes a bunch of dependabot issues too.
=> Update react native devDependency versions

__tests__/index.test.js, scripts/setupJest.js
See https://github.com/RevenueCat/purchases-hybrid-common/pull/685, https://github.com/RevenueCat/purchases-hybrid-common/pull/686, and https://github.com/RevenueCat/purchases-hybrid-common/pull/690.
The main changes were in those PRs. This just updates the stub data to reflect that.
Fixes #659
=> `purchasePackage`: add `StoreTransaction` in `MakePurchaseResult`

apitesters/paywalls.tsx, examples/purchaseTesterTypescript/app/RootStackParamList.tsx, examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx, examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx, examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx, examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt, react-native-purchases-ui/ios/PaywallViewManager.m, react-native-purchases-ui/ios/PaywallViewWrapper.m, react-native-purchases-ui/ios/RCPaywallFooterViewManager.m, react-native-purchases-ui/src/index.tsx
Depends on https://github.com/RevenueCat/purchases-ios/pull/3592/
Add an `options` prop to pass an Offering to the Paywall and Footer Paywall view
=> Add `offering` option to paywall views

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
We have the same empty functions in `RNPurchasesModule.java` to prevent the warning https://github.com/RevenueCat/react-native-purchases/blob/138d2bf05a0c0770f195ef73dd21f060718fed31/android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java#L73
=> Remove 'new NativeEventEmitter() was called with a non-null argument'

react-native-purchases-ui/src/index.tsx
Trying to add a more meaningful error message if RNPaywalls is null. Related to #857
=> Throw error if null module

examples/purchaseTesterTypescript/package.json, yarn.lock
Purchase tester was bringing an outdated dependency that was bringing an old version of `json5` which had some vulnerabilities. This shouldn't affect our SDK, since it was only in our sample app. This updates that version to the latest.
=> Upgrade purchase tester dependencies to upgrade JSON5

apitesters/paywalls.tsx, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/FontAssetManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt, react-native-purchases-ui/ios/PaywallViewWrapper.m, react-native-purchases-ui/src/index.tsx
Thank you for contributing to react-native-purchases. Before pressing the "Create Pull Request" button, please provide the following:
This PR adds a fontFamily string in PaywallOptions Prop, which enables the developers to change the font for the paywall to their custom font.
```typescript
export interface PaywallViewOptions {
offering?: PurchasesOffering | null;
fontFamily?: String | null; // New
}
```
This is the RN native module update for following PR's https://github.com/RevenueCat/purchases-ios/pull/3628 AND https://github.com/RevenueCat/purchases-android/pull/1589
=> [EXTERNAL] Adding fontFamily from RN to CustomFontProvider in PaywallView (contributed by @Jjastiny)

react-native-purchases-ui/ios/PaywallViewWrapper.m
Hoping this will help with https://github.com/RevenueCat/react-native-purchases/issues/914
My theory is that for some reason the JS size of the view is 0, but the iOS view is being rendered.
=> Add some logs on sizing of the PaywallViewWrapper

__tests__/index.test.js, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, apitesters/offerings.ts, apitesters/paywalls.tsx, apitesters/purchases.ts, examples/purchaseTesterTypescript/app/APIKeys.tsx, examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx, examples/purchaseTesterTypescript/app/components/InputModal.tsx, examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx, examples/purchaseTesterTypescript/ios/Podfile.lock, ios/RNPurchases.m, react-native-purchases-ui/package.json, scripts/setupJest.js, src/purchases.ts, yarn.lock
Bump to PHC `10.1.0` and add support for new Targeting methods
Get an offering specific to the place of your paywall (eg: onboarding, settings, feature gate, etc). This is determined by Targeting.
```ts
let offering = await Purchases.getCurrentOfferingForPlacement("your-placement-identifier")
if (offering) {
// Navigate to paywall
} else {
// Do nothing or continue to another screen
}
```
A blocking call to sync attributes and fetch new offerings to to be used with Targeting that uses Custom Attributes.
```ts
// Using this result is optional - offerings will be cached for next Purchases.getOfferings() call
let offerings = await Purchases.syncAttributesAndOfferingsIfNeeded()
```
=>  Adds`Purchases.getCurrentOfferingForPlacement(placementID)` and `Purchases.syncAttributesAndOfferingsIfNeeded()`

fastlane/Fastfile
`is_hotfix` is missing in `generate_docs`. Followup on https://github.com/RevenueCat/react-native-purchases/pull/937/files
https://app.circleci.com/pipelines/github/RevenueCat/react-native-purchases/3421/workflows/8f49fda8-fbbb-4049-bee7-71cfa5055295/jobs/13138
=> Fix `generate_docs`

fastlane/Fastfile
We added Podfile.lock to be able to use iOS caches in https://github.com/RevenueCat/react-native-purchases/commit/dbd26a394cad330a8e17c719a32b73207f06e429
But we were not updating the file when updating phc
I added a private function that will update the Pod, with a retry, because it's possible the Pod is not distributed yet
=> Update Podfile.lock when upgrading phc

examples/purchaseTesterTypescript/android/app/build.gradle, examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainApplication.kt, examples/purchaseTesterTypescript/ios/Podfile, examples/purchaseTesterTypescript/ios/Podfile.lock
Several reasons for the removal:
- We don't use it
- I keep hitting an issue in iOS that Flipper uses a missing function
- It removes 10 iOS dependencies
- The sample for the next version of RN doesn't have Flipper
=> Remove flipper from tester

ios/RNPurchases.m
Fixes #949
There was an extra `presentedOfferingIdentifier` in the `RCT_REMAP_METHOD` for `purchaseProduct`
=> Fix issue with iOS purchaseProduct arguments

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallEventName.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/ViewExtensions.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnDismissEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseCancelledEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseCompletedEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseErrorEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseStartedEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnRestoreCompletedEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnRestoreErrorEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnRestoreStartedEvent.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/PaywallEvent.kt
I've been trying against 0.74 RC with Bridgeless mode and the library doesn't work well on Android. The reason is that the library is using the deprecated RCTEventEmitter.
This PR https://github.com/DylanVann/react-native-fast-image/pull/1032 is an example of another plugin making the same change
=> Remove usage of RCTEventEmitter in Android

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
`ThemedReactContext` is broken in the new architecture. This fix suggested by @cortinico prevents a crash in the new architecture. The behavior is the same
The PaywallFooter is still broken and `themedReactContext.getNativeModule(UIManagerModule::class.java)` is throwing 
```
com.facebook.react.bridge.ReactNoCrashBridgeNotAllowedSoftException: getNativeModule(UIManagerModule.class) cannot be called when the bridge is disabled
```
=> Use ReactContext instead of ThemedReactContext in PaywallFooterViewManager

__tests__/index.test.js, src/purchases.ts
Fix `purchaseDiscountedPackage` not working and getting:
```
Couldn't find package, {underlyingErrorMessage: , userCancelled: false, message: Couldn't find package, code: 5}, null)
```
=> Fix `purchaseDiscountedPackage`

examples/MagicWeather/src/components/PackageItem/index.js
General cleanup of the React Native PackageItem component example.
- remove undeclared style
- update the reference to the deprecated property in the catch statement
- replace purchaserInfo with customerInfo as the MakePurchaseResult type returns from the purchasePackage promise
=> Refactor magicweather package item

examples/MagicWeather/src/components/PackageItem/index.js
General cleanup of the React Native PackageItem component example.
- remove undeclared style
- update the reference to the deprecated property in the catch statement
- replace purchaserInfo with customerInfo as the MakePurchaseResult type returns from the purchasePackage promise
contributed by @onamfc in #1001
=> [EXTERNAL] Refactor magicweather package item via #1001 @onamfc

fastlane/Fastfile
As the title says. Related: https://github.com/RevenueCat/purchases-kmp/pull/93/files/18a33f8b81fd4a8ea81225090874dc9565be3e41#r1642261673.
=> get_phc_version now also checks PHC UI versions

__tests__/index.test.js, src/purchases.ts
Setting a proxy URL doesn't require an instance so we shouldn't be checking if Purchases is configured
=> Setting `proxyURL` should not require configure

android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, ios/RNPurchases.m, src/purchases.ts
This makes the setProxyURL call return the promise so we can await it before calling configure, as the async nature may mean the native bridge hasn't been called before we continue
=> [EXTERNAL] Make the setProxyURL a promise to wait for the native code to set the proxy URL (#1033) contributed by @dangilbert

README.md
The instructions under the "Installation" section mentioned steps to be taken when a project uses ExpoKit. ExpoKit has been deprecated and removed from the Expo ecosystem, thus, making these instructions outdated.
The new instructions only require creating a development build when using the Expo framework in React Native projects. I've added links to creating a project and also for creating a development build that walks through all the essential steps required to create a development build. Also, added the section for Bare workflow (if any of the project uses it and might want to use Expo inside, the docs links mentioned in this section will help them).
After a project is created with Expo, only the library's installation command is required to run.
=> docs: Update installation instructions for Expo

__tests__/index.test.js, android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java, scripts/setupJest.js, src/purchases.ts
Somehow, deprecating the syncObserverModeAmazonPurchase function broke the getPromotionalOffer tests. I redid the changes here and got them working :D
=> replace syncObserverModeAmazonPurchase with syncAmazonPurchase

src/purchases.ts
This PR refines the logging related to the `storeKitVersion` in the `configure()` function. Specifically, it:
- Only logs a message about the storeKitVersions being passed conflicting if the `storeKitVersion` param is not the default value. This should prevent confusion in the event that a developer passes in a `PurchasesAreCompletedByMyApp` but doesn't pass in a `storeKitVersion` param
- If the `storeKitVersion` passed into `PurchasesAreCompletedByMyApp` is the default value, it logs a warning letting the developer know that they should provide a specific `storeKitVersion` that matches what they're using in their StoreKit implementation.
=> Refine StoreKitVersion logging in configure function

src/purchases.ts
Updates the deprecation message of `allowSharingAppStoreAccount` to tell people who are already using the field to continue using it and not remove it.
=> Update allowSharingAppStoreAccount deprecation message

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
This fixes https://github.com/RevenueCat/react-native-purchases/issues/994
Basically when the footer is dismissed within the same view, it triggers a new layout, which since we call a remeasurement with a `post` call, this remeasurement may happen after the view has been removed from the window. This view requires access to the context to be able to obtain the `ViewModel` in the underlying composable, causing a crash.
=> Fix paywall footer dismissal crash

apitesters/purchases.ts, examples/purchaseTesterTypescript/App.tsx, examples/purchaseTesterTypescript/app/RootStackParamList.tsx, examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx, examples/purchaseTesterTypescript/app/screens/WinBackTestingScreen.tsx, examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTester.xcscheme, examples/purchaseTesterTypescript/ios/RevenueCast_PurchaseTesterTypescriptConfiguration.storekit, ios/RNPurchases.m, src/purchases.ts
This PR exposes four new functions to allow developers to fetch & redeem win-back offers that a subscriber is eligible for in their custom paywalls. These functions only function on iOS 18.0+ and require StoreKit 2 to be used.
```typescript
public static async getEligibleWinBackOffersForProduct(
product: PurchasesStoreProduct
): Promise<[PurchasesWinBackOffer] | undefined>
public static async getEligibleWinBackOffersForPackage(
aPackage: PurchasesPackage
): Promise<[PurchasesWinBackOffer] | undefined>
```
```typescript
public static async purchaseProductWithWinBackOffer(
product: PurchasesStoreProduct,
winBackOffer: PurchasesWinBackOffer
): Promise<MakePurchaseResult>
public static async purchasePackageWithWinBackOffer(
aPackage: PurchasesPackage,
winBackOffer: PurchasesWinBackOffer
): …
```
=> Support Fetching and Redeeming Win-Back Offers on Custom Paywall

CHANGELOG.md
We forgot to merge the release PR. This just brings back the changelog to `main`.
=> Add missing 8.5.2 changelog

apitesters/customer_center.tsx, examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx, react-native-purchases-ui/src/index.tsx
This PR fixes the type definition of the `onManagementOptionSelected` callback to accurately reflect its runtime behavior. While this is technically a breaking change in the type system, I believe this should be considered a bug fix rather than requiring a major version bump.
The current type definition incorrectly suggests that the `url` parameter is always a string:
```typescript
onManagementOptionSelected: ({option, url}: {option: CustomerCenterManagementOption, url: string}) => void
```
However, this doesn't match the actual runtime behavior in the native implementations:
iOS:
```objective-c
[self sendEventWithName:@"onManagementOptionSelected" body:@{
@"option": optionID, 
@"url": url ?: [NSNull null]  // url can be null
}];
```
Android:
```kotlin
override fun …
```
=> Fix Typescript definition of onManagementOptionSelected

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
Fixes #1153 
This was caused by an NPE that was a bit hidden.
I managed to find the stacktrace
And noticed that this happens when there are options and offerings is null:
I think this might have started happening on a recent version of RN, if the internal code changed.
=> Fix crash on Paywalls when setting options with null offering

__tests__/index.test.js, apitesters/customerInfo.ts, apitesters/virtualCurrencyInfo.ts, examples/purchaseTesterTypescript/app/screens/CustomerInfoScreen.tsx, scripts/setupJest.js
This PR introduces the ability for developers to fetch virtual currency balances in the React Native SDK through the `CustomerInfo` object. Specifically, the PR:
- Adds the virtual currency APIs to the API testers
- Adds a unit test for parsing the VC balance on CustomerInfo
- Adds the virtual currency balances to the CustomerInfo screen in the purchase test
In addition to the automated tests, I also manually tested the virtual currency balances through the purchase tester app on both iOS and Android.
Once approved, I'll merge this into `virtual-currency-dev`, and will create a beta release from there.
=> Virtual Currency Balances

react-native-purchases-ui/RNPaywalls.podspec
Contributed by @rgomezp in #1246. Original description below.
---------
Fixes #1148 
When installing both `react-native-purchases` and `react-native-purchases-ui` we get a build issue due to the platform targets not lining up.
No unit tests
=> [EXTERNAL] Correctly sets RevenueCatUI podspec platform to `13.0` to fix compatibility issue (#1246) via @rgomezp

__tests__/index.test.js, src/mocks/nativeModule.ts, src/preview/nativeModule.ts, src/purchases.ts, src/utils/environment.ts
Testing a RevenueCat integration in Expo Go was broken: calling any RC API raised an error prompting the Expo Go user to use a development build. This happens because you can’t add custom native code to Expo Go — it's a purely JS app that only works with a fixed set of native modules (like Camera, Notifications, etc. that are precompiled and bundled into the app).
This PR solves that integration:
* react-native-purchases automatically detects whether it's being run in Expo Go.
* When Expo Go is detected, a Preview API Mode is enabled in react-native-purchases.
* In Preview API Mode, all native calls are replaced by Javascript-Level mock APIs.
This way, although the RevenueCat has no real functionality in Expo Go, it allows testing the integration without breaking the development flow of …
=> Preview API Mode for Expo Go

src/purchases.ts
iOS and Android logs are not logged into the JS console. 
This PR sets the native SDK's `logHandler` to a default one that logs every message coming from the native SDKs to the JS console. This way, by default, all logs generated in the native SDKs are now visible in the JS console.
Note that developers can still override the log handler by calling the existing public API `setLogHandler`.
=> Add default log handler

react-native-purchases-ui/src/utils/environment.ts
A small correction on #1272. The presence of native modules in `react-native-purchases-ui` was being checked with 
```ts
if (!!NativeModules.RNPurchases) {
```
This PR changes it to
```ts
if (!!NativeModules.RNPaywalls && !!NativeModules.RNCustomerCenter) {
```
=> Better native modules check for Preview API mode in react-native-purchases-ui

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/views/ComposeViewWrapper.kt
After the fix from #1274 , some folks are reporting their Paywall shows blank an they have to force a recomposition.
I can't reproduce, but hoping that posting the `requestLayout` call would help
=> Posts request layout in `ComposeViewWrapper`

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
Fixes https://github.com/RevenueCat/react-native-purchases/issues/1296
Enforce `presentPaywall` to run on main thread which is needed for https://github.com/RevenueCat/purchases-hybrid-common/pull/1165/files#diff-30371bed0b3177e346fba85b6e89d14baddd42ac5883b2b997840d83790948f1R40
=> Force `presentPaywall` to run on main thread

src/purchases.ts
This PR fixes a typo in the JSDoc comments for `getVirtualCurrencies()`
=> getVirtualCurrencies() JSDoc Typo Fix

examples/purchaseTesterExpo/app/(tabs)/index.tsx, react-native-purchases-ui/src/index.tsx, react-native-purchases-ui/src/preview/previewComponents.tsx
This adds a preview UI for the Customer center to be used when on preview mode (on web mostly). This UI is just a dummy UI used as a placeholder while in this mode. This broke in [#1209](https://github.com/RevenueCat/react-native-purchases/pull/1209/files#diff-d13cb7cc4c8c4d19c22ebd27a4d83b5962c60891a42931f833fb6ee16b5e4dd8R264)
=> Fix `react-native-purchases-ui` preview mode

react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPurchasesConverters.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/views/WrappedPaywallComposeView.kt, react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/views/WrappedPaywallFooterComposeView.kt, react-native-purchases-ui/ios/PaywallViewWrapper.m, react-native-purchases-ui/ios/RNPaywalls.m, react-native-purchases-ui/src/index.tsx
Passing the `PresentedOfferingContext` from the Offering to the PHC APIs when navigating to a paywall. For context see [PHC MR](https://github.com/RevenueCat/purchases-hybrid-common/pull/1246)
=> Passing the PresentedOfferingContext from the Offering to the PHC APIs when navigating to a paywall

.circleci/config.yml
When triggering the CI pipeline with the `bump` action, what we intend is to deploy **the next version** of this dependency. Therefore, the `deploy` workflow should never be triggered in this scenario, since it starts the deployment of **the current version** of the dependency.
This happened to me when trying to release a new version for an older major of PHC. I wanted to release PHC v14.3.0 starting off of v14.2.0. For that I created a `release/14.2.0` branch at the `14.2.0` tag and run the pipeline with the `bump` action. That triggered the `trigger_bump` workflow (as expected) that created the `14.3.0` tag. However, it also triggered the `deploy` workflow because the branch was called `release/X.Y.Z`. 
With this new condition, the `deploy` workflow would'n have been triggered, which is …
=> [V8] [CI] `bump` pipeline action won't trigger `deploy` workflow

fastlane/Fastfile
Passes the `current_version` parameter to the `determine_next_version_using_labels` fastlane action.
=> [V8] Pass current version to determine next version action

.circleci/config.yml, react-native-purchases-ui/apitesters/customer_center.tsx, react-native-purchases-ui/apitesters/paywalls.tsx, react-native-purchases-ui/apitesters/tsconfig.json, react-native-purchases-ui/package.json, react-native-purchases-ui/tsconfig.json
We're evolving customer center, so it's worth having some APITests for this.
- Added TypeScript API tester files for `react-native-purchases-ui`, to assert paywall and customer center callback shapes.
=> Add APITests for UI
