android/src/main/java/com/reactlibrary/RNPurchasesModule.java
ios/SKProduct+RNPurchases.m

Add the currency code to the product info.

[FINAL] Currency Code

---

.watchmanconfig
README.md
android/build.gradle
android/src/main/java/com/reactlibrary/RNPurchasesModule.java
index.js
ios/RNPurchases.m
package.json

Changes the way we setup listeners and adds support for `addAttribution` methods.

[FINAL] API Improvements

---

README.md
index.js

Misc JS Cleanup

---

android/src/main/java/com/reactlibrary/RNPurchasesModule.java

It was only giving the integral part.
I talked to you initially about the incorrect division (from 1000 instead of 1000000) but then overlooked this conversion detail 😅

Fix android price conversion

---

CHANGELOG.md
RNPurchases.podspec
android/build.gradle
android/src/main/java/com/reactlibrary/RNPurchasesModule.java
index.js
ios/RNPurchases.m
package.json

This brings the new identify, create alias and reset calls and updates the sdks to the latest versions

Updates sdk to 1.5.0

---

.circleci/config.yml
.eslintignore
.eslintrc.js
__tests__/index.test.js
example/App.js
example/index.js
example/metro.config.js
example/package.json
example/rn-cli.config.js
example/yarn.lock
index.js
package.json
yarn.lock

This PR adds ESLint and Prettier to the project. I also fixed all the problems that showed up

ESlint and prettier

---

RNPurchases.podspec
android/build.gradle
build.js
index.js
ios/RNPurchases.m
package.json

- Upgrades iOS to 2.4.0
- Upgrades Android to 2.3.0
- Adds Facebook as attribution method
- Adds automatic Apple Ads collection for iOS

Update iOS to 2.4.0 and Android to 2.3.0

---

android/src/main/java/com/reactlibrary/RNPurchasesModule.java

Should fix https://docs.revenuecat.com/discuss/5d42e22a89418f00c5e96534
In Android, trials and introductory prices are different fields in SKUDetails (not in iOS). This PR overrides the intro price information in Android with the trial information. Drawback of doing this is that if someone wants to use both the trial and the intro price, they would not have access to the intro price information. Probably no one is doing this since iOS doesn't support such a thing.

Fixes Android's trial information not being sent down

---

index.d.ts
index.js
src/index.ts

Related to https://github.com/RevenueCat/react-native-purchases/issues/72

Exports enums

---

index.js
package.json
src/index.ts
tsconfig.json

* fix copy/paste issue in error message
* added `watch: true` to config so that when you run build it starts watching for changes and compiles typescript automatically.

[final] fix a copy paste issue in an error message

---

src/index.ts

Hi - I noticed that the typescript definition of availablePackages is wrong.
`readonly availablePackages: [PurchasesPackage];` should be
`readonly availablePackages: PurchasesPackage[];`
two other arrays changed as well

fix: TypeScript: apply correct array notation: [type] to type[]

---

index.d.ts
index.js
src/index.ts

I realized the name was inconsistent

Renames setProxyURLString to setProxyURL

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Bug Report template:
There are certain project specific issues that are commonly misinterpreted as bugs.
- [Offerings, products, or available packages are empty](https://support.revenuecat.com/hc/en-us/articles/360041793174)
- [Invalid Play Store credentials errors](https://support.revenuecat.com/hc/en-us/articles/360046398913)
- [Unable to connect to the App Store (STORE_PROBLEM) errors](https://support.revenuecat.com/hc/en-us/articles/360046399333)
For support I'd recommend our [online community](https://spectrum.chat/revenuecat), [StackOverflow](https://stackoverflow.com/tags/revenuecat/) and/or [Help Center](https://support.revenuecat.com/hc/en-us) 👍
If you have a clearly defined bug (with a [Minimal, Complete, and Reproducible …

Adds issue templates

---

package.json

Adding a few keywords for better discoverability.

Update npm description

---

examples/purchaseTester/ios/Podfile.lock
examples/purchaseTester/metro.config.js
examples/purchaseTester/package.json
examples/purchaseTester/rn-cli.config.js
examples/purchaseTester/yarn.lock
package.json

We had some security alerts in the example so I updated the versions to fix them.

Updates versions in purchaseTester

---

android/gradle.properties

Continuation on https://github.com/RevenueCat/react-native-purchases/pull/251

Removes unnecessary gradle property

---

examples/MagicWeather/ios/MagicWeatherReactNative.xcodeproj/project.pbxproj
examples/MagicWeather/ios/Podfile
examples/MagicWeather/ios/Podfile.lock
examples/MagicWeather/package.json
examples/MagicWeather/yarn.lock
examples/purchaseTester/android/build.gradle
examples/purchaseTester/ios/Podfile.lock
examples/purchaseTester/ios/ReactNativeSample.xcodeproj/project.pbxproj

Counterpart of https://github.com/RevenueCat/react-native-purchases/pull/258/files?file-filters%5B%5D=.json&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension for MagicWeather

Fixed MagicWeather and Xcode 12.5

---

RNPurchases.podspec
__tests__/index.test.js
android/build.gradle
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
dist/purchases.d.ts
dist/purchases.js
examples/MagicWeather/ios/Podfile.lock
examples/purchaseTester/android/settings.gradle
examples/purchaseTester/ios/Podfile.lock
ios/RNPurchases.m
scripts/setupJest.js
src/purchases.ts

Adds new methods: 
- `logIn`
- `logOut`
Deprecates:
- `identify`
- `reset`
- `setAllowSharingStoreAccount`

feature: identity v3

---

CHANGELOG.md

fix bad link in changelog

---

.github/ISSUE_TEMPLATE/bug_report.md
RELEASING.md

just one reference to develop needed to be updated...just officially made main the default branch

Change contribution guidelines link

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

We were still pointing to Spectrum in the issues and the CONTRIBUTING.md

Update community links

---

.circleci/config.yml
RNPurchases.podspec
__tests__/index.test.js
android/build.gradle
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
dist/errors.d.ts
dist/errors.js
dist/purchases.d.ts
dist/purchases.js
examples/purchaseTester/ios/Podfile.lock
ios/RNPurchases.m
scripts/build.js
scripts/setupJest.js
src/errors.ts
src/purchases.ts

Fixes to help preventing "There is no singleton instance errors"

---

apitesters/attributes.ts
apitesters/enums.ts
apitesters/offerings.ts
apitesters/purchaserInfo.ts
apitesters/purchases.ts
src/purchases.ts

Finishes [CSDK-143]
[CSDK-143]: https://revenuecats.atlassian.net/browse/CSDK-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Finished APITesters

---

android/build.gradle

Fixes [SDKONCALL-53] and #368.
[SDKONCALL-53]: https://revenuecats.atlassian.net/browse/SDKONCALL-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove `jcenter`

---

.circleci/config.yml
fastlane/Fastfile
package.json
scripts/docs/index.html
src/errors.ts
src/purchases.ts
tsconfig.json

Fixes [CSDK-324]
See https://revenuecat.github.io/react-native-purchases-docs/
[CSDK-324]: https://revenuecats.atlassian.net/browse/CSDK-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Documentation generation

---

CHANGELOG.md

This seems to have been missed from https://github.com/RevenueCat/react-native-purchases/pull/374

Note change from setUp to configure

---

android/gradle.properties
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt

Bump kotlin version to same as purchases-android

---

.gitignore
apitesters/purchases.ts

This will fix: https://revenuecats.atlassian.net/browse/CSDK-408. We were missing a few methods in our API tests, this adds those that I could find on a quick search.

Add api tests for a few missing methods

---

examples/MagicWeather/App.js
examples/purchaseTesterTypescript/App.tsx
examples/purchaseTesterTypescript/app/APIKeys.tsx

These small changes will make it easier to use the Amazon store in both of our example apps.

Support amazon in example apps

---

.circleci/config.yml
RNPurchases.podspec
android/build.gradle

**This is an automatic release.**
Updates purchases-hybrid-common to 4.3.1

[AUTOMATIC] Updates purchases-hybrid-common to 4.3.1

---

package.json

https://app.circleci.com/pipelines/github/RevenueCat/react-native-purchases/1470/workflows/5526862a-d406-4d1c-874d-0437b2bd9e35/jobs/4819
Fixes this failures when running tsc

Update typescript version to 4.9.3

---

__tests__/index.test.js
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
apitesters/attributes.ts
ios/RNPurchases.m
scripts/setupJest.js
src/purchases.ts

[CSDK-573]
[CSDK-575]
[CSDK-577]
[CSDK-573]: https://revenuecats.atlassian.net/browse/CSDK-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSDK-575]: https://revenuecats.atlassian.net/browse/CSDK-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSDK-577]: https://revenuecats.atlassian.net/browse/CSDK-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add setFirebaseAppInstanceID, setMixpanelDistinctID, setCleverTapID

---

apitesters/offerings.ts
examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
scripts/setupJest.js
src/offerings.ts

[CSDK-591]
[CSDK-591]: https://revenuecats.atlassian.net/browse/CSDK-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds PurchasesStoreProduct.susbcriptionPeriod

---

DEVELOPMENT.md

They need to be run from the project folder.

`DEVELOPMENT.md`: clarified invocation commands

---

.editorconfig
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesPackage.java
apitesters/enums.ts
apitesters/errors.ts
apitesters/purchases.ts
src/purchases.ts

We had some mixture of 2 and 4 spaces in the typescript and java files and since we have `.editorconfig` with `indent_size = 2` my editor was formatting new code with 2 spaces in the Java files, so I changed the config to format the Java files with 4 spaces.
I reformated everything for consistency

Reformats files

---

src/purchases.ts

Deprecates `usesStoreKit2IfAvailable`, adds description

Deprecate `usesStoreKit2IfAvailable`

---

__tests__/index.test.js
apitesters/enums.ts
src/offerings.ts

Adds `immediateAndChargeFullPrice` proration mode

Add `immediateAndChargeFullPrice` proration mode

---

__tests__/index.test.js
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
apitesters/purchases.ts
examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
ios/RNPurchases.m
scripts/setupJest.js
src/purchases.ts

Adds in-app message APIs that allow to control whether the messages are shown automatically or defer them to a moment of choice

Add in-app message APIs

---

fastlane/Fastfile
fastlane/README.md
package.json
react-native-purchases-ui/android/build.gradle

Updates fastlane file to take into account the new library

Update releasing scripts 

---

.circleci/config.yml

Added yarn cache, that got removed when splitting the library in two

Add Yarn cache

---

.circleci/config.yml
apitesters/paywalls.ts

Add paywalls api tests

---

RNPurchases.podspec
apitesters/paywalls.ts
examples/purchaseTesterTypescript/android/build.gradle
examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
react-native-purchases-ui/RNPaywalls.podspec
react-native-purchases-ui/android/build.gradle
react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
react-native-purchases-ui/ios/RNPaywalls.m
react-native-purchases-ui/package.json
react-native-purchases-ui/src/index.tsx
yarn.lock

This adds a `PAYWALL_RESULT` return value to the `presentPaywall`/`presentPaywallIfNeeded` functions.

Add result present paywall

---

apitesters/paywalls.ts
examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
react-native-purchases-ui/src/index.tsx

Makes functions static inside RevenueCatUI to match `Purchases` functions

Creates RevenueCatUI class with static functions

---

Gemfile.lock
RNPurchases.podspec
android/build.gradle
package.json
react-native-purchases-ui/RNPaywalls.podspec
react-native-purchases-ui/android/build.gradle
react-native-purchases-ui/package.json
yarn.lock

- Updated PHC to 8.10.0
- Updated fastlane plugin to e6ba24780086c2863a59204a200f2280deea66f6

Update PHC and fastlane plugin

---

examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
react-native-purchases-ui/ios/RNPaywalls.m
react-native-purchases-ui/ios/UIView+Extensions.h
react-native-purchases-ui/ios/UIView+Extensions.m
react-native-purchases-ui/src/index.tsx

This should fix the safe area issues.

`PaywallFooterViewManager`: added controller to UIVC hierarchy

---

apitesters/paywalls.ts
examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
react-native-purchases-ui/src/index.tsx

This is so we can easily add more parameters without breaking

Made presentPaywallIfNeeded accept an object 

---

fastlane/Fastfile

Fixes https://app.circleci.com/pipelines/github/RevenueCat/react-native-purchases/2939/workflows/379a61bb-c85b-4606-b26f-c48c5ed8607b/jobs/11112

`Fastlane`: fix `bump_phc_version`

---

examples/purchaseTesterTypescript/android/build.gradle

Added dependency repositories including `mavenLocal`. This helps with local development

Add repositories to `purchaseTesterTypescript` android build.gradle

---

RNPurchases.podspec
android/build.gradle
examples/purchaseTesterTypescript/ios/Podfile
fastlane/Fastfile
package.json
react-native-purchases-ui/RNPaywalls.podspec
react-native-purchases-ui/android/build.gradle
react-native-purchases-ui/ios/PaywallViewManager.m
react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
react-native-purchases-ui/ios/RNPaywalls.h
yarn.lock

Depends on https://github.com/RevenueCat/purchases-hybrid-common/pull/672
See also https://github.com/RevenueCat/purchases-flutter/pull/943

`Paywalls`: separate `PurchasesHybridCommonUI`

---

react-native-purchases-ui/ios/PaywallViewManager.m
react-native-purchases-ui/ios/PaywallViewWrapper.h
react-native-purchases-ui/ios/PaywallViewWrapper.m
react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
react-native-purchases-ui/ios/UIView+Extensions.h
react-native-purchases-ui/ios/UIView+Extensions.m

This simplifies the implementation of #850.

`Paywalls`: extracted `PaywallViewWrapper`

---

apitesters/paywalls.tsx
examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
react-native-purchases-ui/ios/RNPaywalls.m
react-native-purchases-ui/src/index.tsx

Depends on https://github.com/RevenueCat/purchases-hybrid-common/pull/670 and https://github.com/RevenueCat/purchases-hybrid-common/pull/666

Add Offering option to paywall functions

---

react-native-purchases-ui/RNPaywalls.podspec
react-native-purchases-ui/ios/PaywallViewWrapper.m
react-native-purchases-ui/ios/RNPaywalls.h
react-native-purchases-ui/ios/RNPaywalls.m

See https://github.com/RevenueCat/react-native-purchases/pull/858#discussion_r1464559861

`RNPaywalls.podspec`: remove `PurchasesHybridCommon` dependency

---

RNPurchases.podspec
android/build.gradle
package.json

Bump PHC 6.3.1

---

examples/purchaseTesterTypescript/Gemfile
examples/purchaseTesterTypescript/Gemfile.lock

I was getting issues with version 0.15.0 of cocoapods

Update cocoapods in Gemfile 

---

apitesters/paywalls.tsx
examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallEvent.kt
react-native-purchases-ui/ios/PaywallViewManager.m
react-native-purchases-ui/ios/PaywallViewWrapper.h
react-native-purchases-ui/ios/PaywallViewWrapper.m
react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
react-native-purchases-ui/src/index.tsx

Depends on https://github.com/RevenueCat/purchases-hybrid-common/pull/735

Add `onPurchaseStarted` event

---

.circleci/config.yml
examples/purchaseTesterTypescript/.gitignore
examples/purchaseTesterTypescript/Gemfile.lock
examples/purchaseTesterTypescript/ios/Podfile.lock

Fix iOS caches

---

CHANGELOG.latest.md
CHANGELOG.md

Made a little more clear the behavior change

Update changelog to include behavior change

---

.circleci/config.yml
fastlane/Fastfile

`update_sample_podfile_lock_with_retry` was failing with missing `sample_path`

Fix pod install of sample when updating phc

---

apitesters/paywalls.tsx
react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/FontAssetManager.kt
react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
react-native-purchases-ui/ios/RNPaywalls.m
react-native-purchases-ui/src/index.tsx

Depends on https://github.com/RevenueCat/purchases-hybrid-common/pull/769/ and https://github.com/RevenueCat/purchases-android/pull/1650/files
Similar to #916 but with presentPaywall functions

Add font support to presentPaywall 

---

RNPurchases.podspec
ios/RNPurchases.m
package.json
yarn.lock

Add TV Os support for expo projects and fixes https://github.com/RevenueCat/react-native-purchases/issues/947

Add TVOS support for Expo apps

---

examples/purchaseTesterTypescript/package.json
package.json
yarn.lock

Fixes https://github.com/RevenueCat/react-native-purchases/security/dependabot/35 by regenerating the yarn.lock
https://github.com/advisories/GHSA-3h5v-q93c-6h6q

Fix ws affected by a DoS

---

RNPurchases.podspec
__tests__/index.test.js
android/build.gradle
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
apitesters/purchases.ts
examples/purchaseTesterTypescript/ios/Podfile.lock
examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/project.pbxproj
ios/RNPurchases.m
package.json
react-native-purchases-ui/RNPaywalls.podspec
react-native-purchases-ui/android/build.gradle
react-native-purchases-ui/package.json
src/purchases.ts
yarn.lock

Contains the changes required to consume PHC 12.0.0 in react-native-purchases

Consume PHC 12.0.0

---

RNPurchases.podspec
android/build.gradle
examples/purchaseTesterTypescript/ios/Podfile.lock
fastlane/Fastfile
package.json
react-native-purchases-ui/RNPaywalls.podspec
react-native-purchases-ui/android/build.gradle
react-native-purchases-ui/package.json
yarn.lock

Updates purchases-hybrid-common to 13.0.1

Updates purchases-hybrid-common to 13.0.1

---

migrations/v8-MIGRATION.md

Typo fix in v8-MIGRATION.md

---

__tests__/index.test.js
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
apitesters/attributes.ts
ios/RNPurchases.m
scripts/setupJest.js
src/purchases.ts

This adds support for Kochava and Tenjin attribute methods

Support Kochava and Tenjin integrations

---

__tests__/index.test.js
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
apitesters/purchases.ts
examples/purchaseTesterTypescript/App.tsx
examples/purchaseTesterTypescript/android/app/src/main/AndroidManifest.xml
examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.mm
examples/purchaseTesterTypescript/ios/PurchaseTester/Info.plist
ios/RNPurchases.m
scripts/setupJest.js
src/purchases.ts

This adds support for Web Redemption Links in our RN SDK.

Support Web Redemption Links

---

RNPurchases.podspec
__tests__/index.test.js
android/build.gradle
android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
apitesters/purchases.ts
examples/purchaseTesterTypescript/App.tsx
examples/purchaseTesterTypescript/ios/Podfile.lock
ios/RNPurchases.m
package.json
react-native-purchases-ui/RNPaywalls.podspec
react-native-purchases-ui/android/build.gradle
react-native-purchases-ui/package.json
src/purchases.ts
yarn.lock

Add diagnostics support

---

ios/RNPurchases.m

Fix get products in iOS

---

src/browser/nativeModule.ts

Add purchases-js `setLogHandler`  to the browser's native module

Implement log handler
